~/chess/cutechess-cli-1.2.0-linux64/cutechess-cli/cutechess-cli.sh -concurrency 2 \
  -pgnout ~/chess/counter41selfrandom.pgn \
  -engine conf=counter41 tc="inf" depth=10 \
  -engine conf=counter41 tc="inf" depth=10 \
  -ratinginterval 10 \
  -event SELF_PLAY_GAMES \
  -draw movenumber=40 movecount=10 score=20 \
  -resign movecount=5 score=1000 \
  -resultformat per-color \
  -openings order=sequential start=1 format=epd file=~/chess/openings/openings_random.epd \
  -each proto=uci option.Hash=32 \
  -rounds 100000
